n = 3
train_price = 5.0
total_budget = 30.0

[track_costs]
v = 1
dim = [3, 3]
data = [0.0, 1.0, 2.0, 1.0, 0.0, 3.0, 2.0, 3.0, 0.0]

[track_times]
v = 1
dim = [3, 3]
data = [0.0, 3.0, 2.0, 3.0, 0.0, 4.0, 2.0, 4.0, 0.0]

[travel_frequencies]
v = 1
dim = [3, 3]
data = [0.0, 5.0, 1.0, 5.0, 0.0, 2.0, 1.0, 2.0, 0.0]
